name: Firebase Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16'
    - name: Install Dependencies
      run: npm install
    - name: Firebase Login
      uses: w9jds/firebase-action@v1.3.0
      with:
        args: login:ci
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Firebase Deploy
      uses: w9jds/firebase-action@v1.3.0
      with:
        args: deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
